USE [master]
GO

/****** Object:  Database [iotOpc]    Script Date: 07-May-19 15:33:15 ******/
CREATE DATABASE [iotOpc]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'iotOpc', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS14\MSSQL\DATA\iotOpc.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'iotOpc_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS14\MSSQL\DATA\iotOpc_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [iotOpc] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [iotOpc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [iotOpc] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [iotOpc] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [iotOpc] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [iotOpc] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [iotOpc] SET ARITHABORT OFF 
GO

ALTER DATABASE [iotOpc] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [iotOpc] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [iotOpc] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [iotOpc] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [iotOpc] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [iotOpc] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [iotOpc] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [iotOpc] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [iotOpc] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [iotOpc] SET  DISABLE_BROKER 
GO

ALTER DATABASE [iotOpc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [iotOpc] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [iotOpc] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [iotOpc] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [iotOpc] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [iotOpc] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [iotOpc] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [iotOpc] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [iotOpc] SET  MULTI_USER 
GO

ALTER DATABASE [iotOpc] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [iotOpc] SET DB_CHAINING OFF 
GO

ALTER DATABASE [iotOpc] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [iotOpc] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [iotOpc] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [iotOpc] SET QUERY_STORE = OFF
GO

ALTER DATABASE [iotOpc] SET  READ_WRITE 
GO


USE [iotOpc]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DailyProduction](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TimeStamp] [datetime2](7) NOT NULL,
	[NumPieces] [numeric](18, 0) NOT NULL,
	[NumPiecesRejected] [numeric](18, 0) NOT NULL,
 CONSTRAINT [PK_DailyProduction] PRIMARY KEY CLUSTERED 
(
	[TimeStamp] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO




CREATE TABLE [dbo].[PlantStateDuration](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TimeStamp] [datetime] NOT NULL,
	[OffDuration] [time](7) NOT NULL,
	[OnRunningDuration] [time](7) NOT NULL,
	[OnStoppedfDuration] [time](7) NOT NULL,
 CONSTRAINT [PK_PlantStateDuration] PRIMARY KEY CLUSTERED 
(
	[TimeStamp] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO





USE [iotOpc]
GO

/****** Object:  Table [dbo].[PlantStates]    Script Date: 07-May-19 15:34:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PlantStates](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TimeStamp] [datetime2](7) NOT NULL,
	[PlantState] [int] NOT NULL,
 CONSTRAINT [PK_PlantStates] PRIMARY KEY CLUSTERED 
(
	[TimeStamp] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

